from selenium.webdriver.common.by import By

HEADER_LOGIN_BUTTON = (By.XPATH, "//div[contains(@class, 'responseHead-module-button')]")
EMAIL_FIELD = (By.NAME, 'email')
PASSWORD_FIELD = (By.NAME, 'password')
WRAP_LOGIN_BUTTON = (By.XPATH, '//div[contains(@class, "authForm-module-button")]')
USERNAME = (By.XPATH, '//div[contains(@class, "userNameWrap")]')
HEADER_BUTTON = (By.XPATH, '//div[contains(@class, "rightButton")]')
LOGOUT_BUTTON = (By.XPATH, '//a[contains(@href, "/logout")]')
MAIN_PAGE_DIV = (By.XPATH, '//div[contains(@class, "mainPage-module-page")]')
ENTER_EMAIL_OR_PHONE_ERROR = (By.XPATH, '//div[contains(@class, "notify-module-error")]')
LOGIN_FORM_MESSAGE = (By.XPATH, '//form/div/div[contains(@class, "formMsg")]')
LOGIN_FORM_MESSAGE_TITLE = (By.XPATH, '//div[contains(@class, "formMsg_title")]')
LOGIN_FORM_MESSAGE_TEXT = (By.XPATH, '//div[contains(@class, "formMsg_text")]')
PROFILE_BUTTON = (By.XPATH, '//a[contains(@class, "center-module-profile")]')
BALANCE_BUTTON = (By.XPATH, '//a[contains(@class, "center-module-billing")]')
PROFILE_ATTR = (By.XPATH, '//div[contains(@class, "profile__title")]')
BALANCE_ATTR = (By.XPATH, '//div[contains(@class, "deposit__payment-form__title")]')
INN_FIELD = (By.XPATH, '//div[contains(@data-name, "ordInn")]/div/input')
PHONE_FIELD = (By.XPATH, '//div[contains(@data-name, "phone")]/div/input')
SAVE_PROFILE_BUTTON = (By.XPATH, '//button[contains(@class, "button_submit")]')
INFORMATION_CHANGED_MESSAGE = (By.XPATH, '//div[contains(@data-class-name, "Success")]/div')
