AUTHORIZATION_LOCATION = 'login'
LOGOUT_LOCATION = 'logout'
POST_CREATE_USER_LOCATION = 'api/user'
DELETE_USER_LOCATION = 'api/user/{username}'
PUT_CHANGE_PASSPORT_LOCATION = 'api/user/{username}/change-password'
POST_BLOCK_USER_LOCATION = 'api/user/{username}/block'
POST_ACCEPT_USER_LOCATION = 'api/user/{username}/accept'
GET_STATUS_LOCATION = 'status'
